### ISSUE TITLE
Overwrite Ctrl+Space

### ISSUE THREAD

**Issue by ElyeM** [ralphite/ClipBoard#14]
Add option (Menu >> Settings) to overwrite Ctrl+Space HotKey.

**Comment by MrCull** [comment]
Yeah it would be great to make this configurable.

**Comment by viper3400** [comment]
In a basic version this is implemented in my development branch. https://github.com/viper3400/ClipBoard/tree/develop

For the moment it is just possible to change the second key, but not the CTRL key. See readme in my development branch.

You may use build binaries for testing: https://ci.appveyor.com/project/viper3400/clipboard/build/0.0.0.4/artifacts

**Comment by MrCull** [comment]
Confirmed this is now resolved. 
I'll try and make a new release soon @ElyeM
