### ISSUE TITLE
Form Won't Resize When Beeing Restored From Windows Tray

### ISSUE THREAD

**Issue by viper3400** [ralphite/ClipBoard#16]
see issue at https://github.com/viper3400/ClipBoard/issues/5, already fixed in my master branch 
see PR https://github.com/ralphite/ClipBoard/pull/13

**Comment by MrCull** [comment]
Its great to see more contributions :)
I have verified this bug and that your fix resolved this.
Will merge in PR #13 ...

**Comment by viper3400** [comment]
Should be resolved with PR#13 in commit b33db10121c9155866a38cde6c1fd760c35a0095.
