### ISSUE TITLE
Auto run on start-up

### ISSUE THREAD

**Issue by MrCull** [ralphite/ClipBoard#17]
Currently on one of my PCs have have configured this App to start on start-up via the "Task Scheduler".

On another PC I have not done this. It somewhat annoys me that this doe snot run on start up but I have not made this the same configuration as above because I think the App should prompt on first run if the user would like it to run after every logoff/logon.

So my User Story is...
As a CpliBoard User
I want the application to auto run after a PC reboot
So that I don't have to manually run this app (after I have probably tried to past something and then realised that it's not currently running and already lost what I thought has been saved)

**Comment by viper3400** [comment]
Implemented in my development branch. https://github.com/viper3400/ClipBoard/tree/develop

**Comment by MrCull** [comment]
Your Dev branch is looking sweet :)

**Comment by MrCull** [comment]
Great work!
Confirm this is now implemented.
